# Generated by Django 4.2.11 on 2024-03-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=128)),
                ('user_birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.user')),
                ('order_products', models.ManyToManyField(to='secondapp.product')),
            ],
        ),
    ]
